api:
  tws_endpoint: "127.0.0.1"
  port: 7497

technical_analysis:
  sma_period: 20
  ema_period: 20
  vwap_period: 14
  rsi_period: 14
  macd_fast_period: 12
  macd_slow_period: 26
  macd_signal_period: 9
  bollinger_bands_period: 20
  bollinger_bands_std_dev: 2
  atr_period: 14
  adx_period: 14
  cci_period: 20

risk_management:
  max_position_size: 100
  daily_loss_limit: 1000
  max_trade_frequency: 10
