# Production configuration file for trading bot

# General settings
general:
  log_level: INFO
  log_file: logs/trading_bot_prod.log

# API settings
api:
  reconnect_attempts: 5
  reconnect_backoff: 2
  tws_endpoint: 127.0.0.1
  port: 7497

# Data settings
data:
  buffer_size: 1000
  historical_data_path: data/historical/
  time_series_db: influxdb://localhost:8086

# Technical analysis settings
technical_analysis:
  sma_period: 20
  ema_period: 50
  vwap_period: 14
  rsi_period: 14
  macd_fast_period: 12
  macd_slow_period: 26
  macd_signal_period: 9
  bollinger_bands_period: 20
  bollinger_bands_std_dev: 2

# Qualitative analysis settings
qualitative_analysis:
  sentiment_threshold: 0.5

# Trading settings
trading:
  max_position_size: 100
  daily_loss_limit: 1000
  max_trade_frequency: 10
  volatility_position_sizing: true

# CLI settings
cli:
  refresh_interval: 1
  color_scheme: default
